version: '3.8'

services:
  backend:
    build:
      context: ./backend/inflow
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
      - "5006:5006"
    volumes:
      - ./backend/inflow:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
  frontend:
    build:
      context: ./frontend/ #{service}
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./frontend/service:/app
      - /app/node_modules
    depends_on:
      - backend